### ISSUE TITLE
source file format

### ISSUE THREAD

**Issue by sunt05** [hamidrezaomidvar/SUEWS_parameters_docs#1]
Hi @hamidrezaomidvar , 
I notice you are putting `rst` docs in as source files: I suggest we use the `ipynb` files as they require less work and people can easily reuse those files for their applications. 
How do you think?

**Comment by hamidrezaomidvar** [comment]
Yes, this is the plan. But I would need a simpler version of the `ipynb` files as some of them takes time to run and we will have problem uploading them.
