### ISSUE TITLE
extension `nbsphinx`

### ISSUE THREAD

**Issue by sunt05** [hamidrezaomidvar/SUEWS_parameters_docs#2]
It's blank here:
https://github.com/hamidrezaomidvar/SUEWS_parameters_docs/blob/b75c02eab9e180eadb3f31a8730e892328aacaf8/docs/source/conf.py#L33-L34

we can use [nbsphinx](https://nbsphinx.readthedocs.io/en/0.5.1/) to resolve #1 .

**Comment by hamidrezaomidvar** [comment]
Got it. Thanks!
